server:
  port: 9090

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
#暴露的接口
management:
  endpoints:
    web:
      exposure:
        include: '*'




