server:
  port: 80
eureka:
  client:
    #表示将自己注册到注册中心eurekaServer
    register-with-eureka: true
    #是否抓取eurekaServer以有的注册信息，默认为true
    fetchRegistry: true
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
spring:
  application:
    name: cloud-order-server
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 1
